import type {
  Course,
  FamilyMetrics,
  NotificationItem,
  Student,
  StudyTask,
  StudyTest,
  Submission,
  Workbook,
} from "@/lib/domain/types";

export const demoStudents: Student[] = [
  {
    id: "student-minseo",
    familyId: "family-demo",
    name: "민서",
    handle: "minseo",
    grade: 2,
    avatar: "🌿",
    color: "#6b5ce7",
    weeklyGoalMinutes: 720,
    streak: 12,
  },
  {
    id: "student-jiwoo",
    familyId: "family-demo",
    name: "지우",
    handle: "jiwoo",
    grade: 1,
    avatar: "🌸",
    color: "#ef7a97",
    weeklyGoalMinutes: 600,
    streak: 7,
  },
];

export const demoTasks: StudyTask[] = [
  {
    id: "task-1",
    familyId: "family-demo",
    studentId: "student-minseo",
    subject: "영어",
    type: "lecture",
    title: "중2 영어 문법 완성",
    detail: "12강 현재완료의 쓰임",
    scheduledDate: "2026-08-06",
    dueTime: "17:30",
    estimatedMinutes: 35,
    status: "approved",
    evidence: ["check", "timer", "memo"],
  },
  {
    id: "task-2",
    familyId: "family-demo",
    studentId: "student-minseo",
    subject: "수학",
    type: "workbook",
    title: "쎈 수학 2-1",
    detail: "88쪽~93쪽, 일차함수 기본문제",
    scheduledDate: "2026-08-06",
    dueTime: "19:00",
    estimatedMinutes: 45,
    status: "submitted",
    evidence: ["timer", "photo", "memo"],
    priority: "high",
  },
  {
    id: "task-3",
    familyId: "family-demo",
    studentId: "student-minseo",
    subject: "영어",
    type: "memorize",
    title: "필수 영단어 30개",
    detail: "Day 18 · achieve ~ feature",
    scheduledDate: "2026-08-06",
    dueTime: "20:00",
    estimatedMinutes: 25,
    status: "in_progress",
    evidence: ["timer", "test"],
  },
  {
    id: "task-4",
    familyId: "family-demo",
    studentId: "student-minseo",
    subject: "과학",
    type: "review",
    title: "광합성 핵심 개념",
    detail: "개념노트 2쪽 작성 후 사진 제출",
    scheduledDate: "2026-08-06",
    dueTime: "21:00",
    estimatedMinutes: 30,
    status: "scheduled",
    evidence: ["photo", "memo"],
  },
  {
    id: "task-5",
    familyId: "family-demo",
    studentId: "student-jiwoo",
    subject: "국어",
    type: "lecture",
    title: "중1 국어 독해",
    detail: "8강 설명문의 구조",
    scheduledDate: "2026-08-06",
    dueTime: "18:00",
    estimatedMinutes: 30,
    status: "approved",
    evidence: ["check", "timer"],
  },
  {
    id: "task-6",
    familyId: "family-demo",
    studentId: "student-jiwoo",
    subject: "수학",
    type: "workbook",
    title: "개념원리 중1",
    detail: "54쪽~59쪽, 정수와 유리수",
    scheduledDate: "2026-08-06",
    dueTime: "19:30",
    estimatedMinutes: 40,
    status: "parent_review",
    evidence: ["timer", "photo"],
  },
  {
    id: "task-7",
    familyId: "family-demo",
    studentId: "student-jiwoo",
    subject: "역사",
    type: "memorize",
    title: "삼국의 성장",
    detail: "교과서 42~47쪽 핵심 사건 암기",
    scheduledDate: "2026-08-06",
    dueTime: "20:30",
    estimatedMinutes: 25,
    status: "scheduled",
    evidence: ["memo", "test"],
  },
];

export const demoSubmissions: Submission[] = [
  {
    id: "submission-1",
    taskId: "task-2",
    familyId: "family-demo",
    studentId: "student-minseo",
    submittedAt: "2026-08-06T09:42:00+09:00",
    note: "91쪽 7번이 어려워서 별표했어요.",
    elapsedMinutes: 47,
    imageUrls: [],
    aiReview: {
      summary: "88~93쪽의 풀이 흔적이 확인되고 대부분 문항이 작성되었습니다.",
      detectedPages: ["88", "89", "90", "91", "92", "93"],
      completionPercent: 94,
      blurScore: 0.08,
      blankAreas: ["91쪽 7번"],
      flags: ["91쪽 7번 미완료 가능성"],
      confidence: 0.92,
      provider: "OpenAI",
      model: "GPT-5.6 Terra",
    },
  },
  {
    id: "submission-2",
    taskId: "task-6",
    familyId: "family-demo",
    studentId: "student-jiwoo",
    submittedAt: "2026-08-06T10:14:00+09:00",
    note: "다 풀었어요!",
    elapsedMinutes: 39,
    imageUrls: [],
    aiReview: {
      summary: "54~59쪽으로 보이며 풀이가 고르게 작성되었습니다. 마지막 사진의 초점이 약합니다.",
      detectedPages: ["54", "55", "56", "57", "58", "59"],
      completionPercent: 88,
      blurScore: 0.31,
      blankAreas: ["59쪽 하단"],
      flags: ["마지막 사진 재확인 필요"],
      confidence: 0.78,
      provider: "Gemini",
      model: "Gemini 2.5 Flash",
    },
  },
];

export const demoTests: StudyTest[] = [
  {
    id: "test-1",
    familyId: "family-demo",
    studentId: "student-minseo",
    subject: "영어",
    title: "Day 18 영단어 테스트",
    scheduledDate: "2026-08-06",
    passScore: 80,
    timeLimitMinutes: 15,
    maxAttempts: 2,
    shuffleQuestions: true,
    status: "published",
    questions: [
      { id: "q1", type: "spelling", prompt: "성취하다", answer: "achieve", points: 20, source: "parent" },
      {
        id: "q2",
        type: "multiple_choice",
        prompt: "feature의 뜻은?",
        choices: ["특징", "실패", "미래", "형태"],
        answer: "특징",
        points: 20,
        source: "ai_draft",
      },
      { id: "q3", type: "dictation", prompt: "음성을 듣고 단어를 쓰세요.", answer: "environment", points: 20, source: "ai_draft" },
      { id: "q4", type: "speaking", prompt: "achievement를 소리 내어 말하세요.", answer: "achievement", points: 20, source: "ai_auto" },
      { id: "q5", type: "spelling", prompt: "환경", answer: "environment", points: 20, source: "parent" },
    ],
  },
  {
    id: "test-2",
    familyId: "family-demo",
    studentId: "student-jiwoo",
    subject: "역사",
    title: "삼국의 성장 암기 확인",
    scheduledDate: "2026-08-07",
    passScore: 80,
    timeLimitMinutes: 20,
    maxAttempts: 2,
    shuffleQuestions: false,
    status: "draft",
    questions: [],
  },
  {
    id: "test-3",
    familyId: "family-demo",
    studentId: "student-minseo",
    subject: "과학",
    title: "광합성 개념 테스트",
    scheduledDate: "2026-08-04",
    passScore: 80,
    timeLimitMinutes: 15,
    maxAttempts: 2,
    shuffleQuestions: true,
    status: "retest",
    latestScore: 72,
    questions: [],
  },
];

export const demoCourses: Course[] = [
  {
    id: "course-1",
    familyId: "family-demo",
    studentId: "student-minseo",
    subject: "영어",
    title: "중2 영어 문법 완성",
    teacher: "엠베스트 영어",
    source: "mbest",
    lessons: Array.from({ length: 24 }, (_, index) => ({ id: `eng-${index + 1}`, index: index + 1, title: `${index + 1}강 핵심 문법` })),
    completedLessonCount: 11,
  },
  {
    id: "course-2",
    familyId: "family-demo",
    studentId: "student-jiwoo",
    subject: "국어",
    title: "중1 국어 독해 기본",
    source: "mbest",
    lessons: Array.from({ length: 18 }, (_, index) => ({ id: `kor-${index + 1}`, index: index + 1, title: `${index + 1}강 독해 원리` })),
    completedLessonCount: 7,
  },
];

export const demoWorkbooks: Workbook[] = [
  { id: "wb-1", familyId: "family-demo", studentId: "student-minseo", subject: "수학", title: "쎈 수학 2-1", unit: "일차함수", currentPage: 88, endPage: 162, targetDate: "2026-08-31" },
  { id: "wb-2", familyId: "family-demo", studentId: "student-jiwoo", subject: "수학", title: "개념원리 중1", unit: "정수와 유리수", currentPage: 54, endPage: 128, targetDate: "2026-09-05" },
];

export const demoMetrics: Record<string, FamilyMetrics> = {
  "student-minseo": { completionRate: 84, onTimeRate: 91, rejectionRate: 6, studyMinutes: 612, averageScore: 87, pendingReviews: 1 },
  "student-jiwoo": { completionRate: 76, onTimeRate: 82, rejectionRate: 9, studyMinutes: 524, averageScore: 81, pendingReviews: 1 },
};

export const demoNotifications: NotificationItem[] = [
  { id: "n1", familyId: "family-demo", recipientId: "demo-parent", title: "새 제출물이 도착했어요", body: "민서가 쎈 수학 88~93쪽을 제출했습니다.", type: "submission", createdAt: "10분 전", read: false },
  { id: "n2", familyId: "family-demo", recipientId: "demo-parent", title: "재시험 제안", body: "광합성 개념 테스트가 72점입니다. 오답 3문항 재시험을 확인하세요.", type: "test", createdAt: "어제", read: false },
  { id: "n3", familyId: "family-demo", recipientId: "demo-parent", title: "주간 리포트가 준비됐어요", body: "두 학생의 지난주 학습 리포트를 확인하세요.", type: "weekly", createdAt: "월요일", read: true },
];
